# Demo Spring application

trigger: none
pr: 
  autoCancel: true
  branches:
    include:
    - none
    exclude:
    - master
pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Junit Stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Running Spring demo app unit test'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true
  - stage: 'BuildArtifact'
    displayName: 'Building Artifact'
    condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'))
    dependsOn: 'Junit'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Building Artifact'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            options: '--no-transfer-progress'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '*.java'
            TargetFolder: '$(build.artifactstagingdirectory)'
            CleanTargetFolder: true
            OverWrite: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
